import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Hero from '../components/hero'
import AboutMe from '../components/aboutMe'
import Projects from '../components/projects'

export default function Home() {
    return (
        <>
            <Head>
                <title>Maveryck Maya</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Hero />
            <AboutMe />
            <Projects />
        </>
    )
}
