import Image from 'next/image'

import Layout from '../components/layout/layout'
import Head from 'next/head'
import Hero from '../components/hero'
import AboutMe from './#about'
import Projects from './#projects'

import styles from '../styles/Home.module.scss'
import { useEffect } from 'react'

export default function Home() {
    // useEffect(() => {
    //     const box = document.getElementById('box')
    //     const pageContainer = document.getElementById('page--container')
    //     box.style.height = `${pageContainer.offsetHeight + 120}px`

    //     if (typeof window !== 'undefined') {
    //         window.addEventListener('resize', () => {
    //             box.style.height = `${pageContainer.offsetHeight + 120}px`
    //         })
    //     }

    //     return () => {
    //         box.style.height = `${pageContainer.offsetHeight + 120}px`

    //         if (typeof window !== 'undefined') {
    //             window.removeEventListener('resize', () => {
    //                 box.style.height = `${pageContainer.offsetHeight + 120}px`
    //             })
    //         }
    //     }
    // }, [])

    return (
        <>
            <Head>
                <title>Maveryck Maya</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                {/* <div className={styles['page--container']} id="page--container"> */}
                <Hero />
                <AboutMe />
                <Projects />
                {/* </div> */}
                {/* <div className={styles['box']} id="box">
                    <Image
                        src="/backgrounds/main-light-background.svg"
                        alt="background decoration"
                        layout="fill"
                        objectFit="cover"
                        quality={100}
                    />
                </div> */}
            </Layout>
        </>
    )
}
